[2024-07-16T04:13:56.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T04:13:56.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_glue_crawler.start_glue_crawler scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T04:13:56.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_glue_crawler.start_glue_crawler scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T04:13:56.090+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T04:13:56.117+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_glue_crawler> on 2024-07-15 00:00:00+00:00
[2024-07-16T04:13:56.130+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'start_glue_crawler', 'start_glue_crawler', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/etl_populate_database.py', '--cfg-path', '/tmp/tmpxziac3vl']
[2024-07-16T04:13:56.126+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T04:13:56.132+0000] {standard_task_runner.py:91} INFO - Job 258: Subtask start_glue_crawler
[2024-07-16T04:13:56.133+0000] {standard_task_runner.py:63} INFO - Started process 83 to run task
[2024-07-16T04:13:56.209+0000] {task_command.py:426} INFO - Running <TaskInstance: start_glue_crawler.start_glue_crawler scheduled__2024-07-15T00:00:00+00:00 [running]> on host 0ec6e6e2bd09
[2024-07-16T04:13:56.356+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='start_glue_crawler' AIRFLOW_CTX_TASK_ID='start_glue_crawler' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T04:13:56.358+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T04:13:56.426+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T04:13:56.427+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_populate_database.py", line 31, in start_glue_crawler
    client = hook.get_client_type('glue', region_name='us-east-2')  # Ensure region_name matches your setup
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AwsGenericHook.get_client_type() got multiple values for argument 'region_name'
[2024-07-16T04:13:56.446+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=start_glue_crawler, task_id=start_glue_crawler, run_id=scheduled__2024-07-15T00:00:00+00:00, execution_date=20240715T000000, start_date=20240716T041356, end_date=20240716T041356
[2024-07-16T04:13:56.469+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 258 for task start_glue_crawler (AwsGenericHook.get_client_type() got multiple values for argument 'region_name'; 83)
[2024-07-16T04:13:56.511+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T04:13:56.540+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T04:13:56.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
